export const CREATE_GAME = 'CREATE_GAME';
export const JOIN_GAME = 'JOIN_GAME';

export const SET_GAME_SIZE = 'SET_GAME_SIZE';
export const SET_FIRST_PLAYER = 'SET_FIRST_PLAYER';
export const SET_SECOND_PLAYER = 'SET_SECOND_PLAYER';

export const GET_AVAILABLE_MOVES = 'GET_AVAILABLE_MOVES';
export const MAKE_MOVE = 'MAKE_MOVE';
export const GET_OPPONENT_MOVE = 'GET_OPPONENT_MOVE';
export const SET_NEXT_TURN = 'SET_NEXT_TURN';
export const SET_PLAYER_OWNED_SQUARE = 'SET_PLAYER_OWNED_SQUARE';
export const SET_OPPONENT_OWNED_SQUARE = 'SET_OPPONENT_OWNED_SQUARE';

export const GAME_OVER = 'GAME_OVER';

export const SHOW_CREATE_GAME_DIALOG = 'SHOW_CREATE_GAME_DIALOG';
export const CLOSE_CREATE_GAME_DIALOG = 'CLOSE_CREATE_GAME_DIALOG';

export const SHOW_JOIN_GAME_DIALOG = 'SHOW_JOIN_GAME_DIALOG';
export const CLOSE_JOIN_GAME_DIALOG = 'CLOSE_JOIN_GAME_DIALOG';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';