export const CREATE_GAME = 'CREATE_GAME';
export const JOIN_GAME = 'JOIN_GAME';

export const SET_FIRST_PLAYER = 'SET_FIRST_PLAYER';
export const SET_SECOND_PLAYER = 'SET_SECOND_PLAYER';

export const GET_AVAILABLE_MOVES = 'GET_AVAILABLE_MOVES';
export const MAKE_MOVE = 'MAKE_MOVE';
export const GET_OPPONENT_MOVE = 'GET_OPPONENT_MOVE';